/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tut1;

import java.sql.*;

import javax.swing.table.*;

/**
 *
 * @author Admin
 */
import javax.swing.table.*;
public class Crud extends javax.swing.JFrame {

    /**
     * Creates new form Crud
     */
    Connection conn = null;
    DefaultTableModel tableModel;
    public Crud() {
        initComponents();
        getConnect();
        get_data();
        
        
    }
    public void getConnect(){
    
     //include driver
        try{
            Class.forName("sun.jdbc.odbc.jdbcodbcDriver");
        }catch(Exception e){
            System.out.println(e);
        }
        
        //connect  to Db 
        
        try{
            String con_string = "jdbc:odbc:Driver={Microsoft Access Driver (*.mdb)};DBQ=D:\\Rushik\\Rushik_J2EE\\Tut2\\Database\\MyStud.mdb";
                conn = DriverManager.getConnection(con_string,"","");
        }catch(Exception e){
            System.out.println(e);
        }
        
        
        System.out.println("Connecction Successfull !!");
    }
    
    public void get_data(){
    try {
            String select_query = "SELECT * FROM Student";
            Statement stmt = conn.createStatement();
            ResultSet rset = stmt.executeQuery(select_query);
            
            while (rset.next()){
                
                int count = tableModel.getRowCount()+1;
                
                tableModel.addRow(new Object[]{rset.getInt("Stud_Id"),rset.getString("Stud_Name"), rset.getDate("Birth_Date"), rset.getString("City"), rset.getString("Course"), rset.getString("Semester"),rset.getInt("Division")});
                
                System.out.println(
                        "Stud ID: " + rset.getInt("Stud_Id") 
                        +"  Stud Name : " + rset.getString("Stud_Name") 
                        + " Birth Date :" + rset.getDate("Birth_Date")
                        + " City :" + rset.getString("City")
                        + " Course : " + rset.getString("Course")
                        + " Semester : " + rset.getString("Semester")
                        + " Division : " + rset.getInt("Division") 
                );                
            }
            stmt.close();
            conn.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Button_Calculate = new javax.swing.JButton();
        TextBox_rollno = new javax.swing.JTextField();
        lable_Mark3 = new javax.swing.JLabel();
        lable_rollno = new javax.swing.JLabel();
        lable_StudentName1 = new javax.swing.JLabel();
        TextBox_Birthdate = new javax.swing.JTextField();
        lable_StudentName = new javax.swing.JLabel();
        TextBox_StudName = new javax.swing.JTextField();
        TextBox_Course = new javax.swing.JTextField();
        TextBox_city = new javax.swing.JTextField();
        lable_Mark2 = new javax.swing.JLabel();
        lable_Mark4 = new javax.swing.JLabel();
        TextBox_Semester = new javax.swing.JTextField();
        lable_Mark5 = new javax.swing.JLabel();
        TextBox_Division = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableModel = new DefaultTableModel( new Object [][] {
        },
        new String [] {
            "Roll No", "Student Name", "Birth Date", "City", "Course", "Semester", "Division"
        });
        jTable1.setModel(tableModel);
        jScrollPane1.setViewportView(jTable1);

        Button_Calculate.setText("Add");
        Button_Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CalculateActionPerformed(evt);
            }
        });

        lable_Mark3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lable_Mark3.setText("Course");

        lable_rollno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lable_rollno.setText("RollNo");

        lable_StudentName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lable_StudentName1.setText("BirthDate");

        lable_StudentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lable_StudentName.setText("Student Name");

        lable_Mark2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lable_Mark2.setText("City");

        lable_Mark4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lable_Mark4.setText("Semester");

        lable_Mark5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lable_Mark5.setText("Division");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lable_Mark4)
                            .addComponent(lable_Mark3)
                            .addComponent(lable_Mark2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lable_rollno)
                                .addGap(68, 68, 68)
                                .addComponent(TextBox_rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lable_StudentName)
                                    .addComponent(lable_StudentName1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextBox_StudName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TextBox_Semester, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TextBox_Course, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextBox_Birthdate, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextBox_city, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lable_Mark5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(TextBox_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(93, 93, 93)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(Button_Calculate)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextBox_rollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_rollno, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextBox_StudName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_StudentName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lable_StudentName1)
                    .addComponent(TextBox_Birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextBox_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_Mark2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextBox_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_Mark3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextBox_Semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_Mark4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextBox_Division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_Mark5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(Button_Calculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CalculateActionPerformed
        // TODO add your handling code here:
        String rollno = TextBox_rollno.getText();
        String studname = TextBox_StudName.getText();
        Integer mark1 = Integer.parseInt(TextBox_Birthdate.getText());
        Integer mark2 = Integer.parseInt(TextBox_city.getText());
        Integer mark3 = Integer.parseInt(TextBox_Course.getText());
        Integer total = mark1 + mark2 + mark3;
        Float percentage = Float.parseFloat(total.toString())/3;

        String outputString = "Rollno: "+rollno;
        outputString += "\n" + "StudentName: " + studname;
        outputString += "\n" + "Mark1: " + mark1;
        outputString += "\n" + "Mark2: " + mark2;
        outputString += "\n" + "Mark3: " + mark3;
        outputString += "\n" + "Total: " + total;
        outputString += "\n" + "Percentage: " + percentage;
        String grd = "";
        if(mark1 >= 35 && mark2 >= 35 && mark3 >= 35){
            if (percentage >= 90) {
                grd = "O";
            }
            else if(percentage >=80 && percentage<=90){
                grd = "A";
            }
            else if(percentage >=70 && percentage<=80){
                grd = "B";
            }
            else if(percentage >=60 && percentage<=70){
                grd = "C";
            }
            else if(percentage >=50 && percentage<=60){
                grd = "D";
            }
            else{
                grd = "E";
            }
        }
        else
        {
            percentage = new Float(0);
            grd = "Fail";
        }

        //int count = tableModel.getRowCount()+1;
        int count = tableModel.getRowCount()+1;
        tableModel.addRow(new Object[]{new Integer(TextBox_rollno.getText()), TextBox_StudName.getText(), new Float(TextBox_Birthdate.getText()), new Float(TextBox_city.getText()), new Float(TextBox_Course.getText()), new Float(percentage)+"%", grd});
        //tableModel.addRow(new Object[]{new Integer(TextBox_rollno.getText()), TextBox_StudName.getText()});

        TextBox_rollno.setText("");
        TextBox_StudName.setText("");
        TextBox_Birthdate.setText("");
        TextBox_city.setText("");
        TextBox_Course.setText("");
    }//GEN-LAST:event_Button_CalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Calculate;
    private javax.swing.JTextField TextBox_Birthdate;
    private javax.swing.JTextField TextBox_Course;
    private javax.swing.JTextField TextBox_Division;
    private javax.swing.JTextField TextBox_Semester;
    private javax.swing.JTextField TextBox_StudName;
    private javax.swing.JTextField TextBox_city;
    private javax.swing.JTextField TextBox_rollno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lable_Mark2;
    private javax.swing.JLabel lable_Mark3;
    private javax.swing.JLabel lable_Mark4;
    private javax.swing.JLabel lable_Mark5;
    private javax.swing.JLabel lable_StudentName;
    private javax.swing.JLabel lable_StudentName1;
    private javax.swing.JLabel lable_rollno;
    // End of variables declaration//GEN-END:variables
}
