/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tut1;

/**
 *
 * @author Admin
 */
public class Tut1_Exe8_MarkSheet1 extends javax.swing.JFrame {

    /**
     * Creates new form Tut1_Exe8_MarkSheet1
     */
    public Tut1_Exe8_MarkSheet1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lable_rollno = new javax.swing.JLabel();
        TextBox_rollno = new javax.swing.JTextField();
        lable_StudentName = new javax.swing.JLabel();
        TextBox_StudName = new javax.swing.JTextField();
        lable_StudentName1 = new javax.swing.JLabel();
        TextBox_Mark1 = new javax.swing.JTextField();
        TextBox_Mark2 = new javax.swing.JTextField();
        lable_Mark2 = new javax.swing.JLabel();
        TextBox_Mark3 = new javax.swing.JTextField();
        lable_Mark3 = new javax.swing.JLabel();
        Button_Calculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lable_rollno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lable_rollno.setText("RollNo");

        lable_StudentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lable_StudentName.setText("Student Name");

        lable_StudentName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lable_StudentName1.setText("Mark1");

        lable_Mark2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lable_Mark2.setText("Mark2");

        lable_Mark3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lable_Mark3.setText("Mark3");

        Button_Calculate.setText("Calculate");
        Button_Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CalculateActionPerformed(evt);
            }
        });

        TextArea_output.setColumns(20);
        TextArea_output.setRows(5);
        jScrollPane1.setViewportView(TextArea_output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lable_Mark2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Button_Calculate)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lable_Mark3)
                            .addGap(172, 172, 172)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lable_rollno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextBox_rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lable_StudentName)
                                .addComponent(lable_StudentName1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextBox_StudName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextBox_Mark3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(TextBox_Mark1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextBox_Mark2, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextBox_rollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_rollno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextBox_StudName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_StudentName))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lable_StudentName1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextBox_Mark1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextBox_Mark2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_Mark2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextBox_Mark3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_Mark3))
                .addGap(28, 28, 28)
                .addComponent(Button_Calculate)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CalculateActionPerformed
        // TODO add your handling code here:
        String rollno = TextBox_rollno.getText();
        String studname = TextBox_StudName.getText();
        Integer mark1 = Integer.parseInt(TextBox_Mark1.getText());
        Integer mark2 = Integer.parseInt(TextBox_Mark2.getText());
        Integer mark3 = Integer.parseInt(TextBox_Mark3.getText());
        Integer total = mark1 + mark2 + mark3;
        Float percentage = Float.parseFloat(total.toString())/3;
        
        String outputString = "Rollno: "+rollno;
        outputString += "\n" + "StudentName: " + studname;
        outputString += "\n" + "Mark1: " + mark1;
        outputString += "\n" + "Mark2: " + mark2;
        outputString += "\n" + "Mark3: " + mark3;
        outputString += "\n" + "Total: " + total;
        outputString += "\n" + "Percentage: " + percentage;
        
        TextArea_output.setText(outputString);
    }//GEN-LAST:event_Button_CalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tut1_Exe8_MarkSheet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tut1_Exe8_MarkSheet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tut1_Exe8_MarkSheet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tut1_Exe8_MarkSheet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tut1_Exe8_MarkSheet1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Calculate;
    private javax.swing.JTextArea TextArea_output;
    private javax.swing.JTextField TextBox_Mark1;
    private javax.swing.JTextField TextBox_Mark2;
    private javax.swing.JTextField TextBox_Mark3;
    private javax.swing.JTextField TextBox_StudName;
    private javax.swing.JTextField TextBox_rollno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lable_Mark2;
    private javax.swing.JLabel lable_Mark3;
    private javax.swing.JLabel lable_StudentName;
    private javax.swing.JLabel lable_StudentName1;
    private javax.swing.JLabel lable_rollno;
    // End of variables declaration//GEN-END:variables
}
