/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tut1;

/**
 *
 * @author Admin
 */
public class Tut1_Exe3_checkbox extends javax.swing.JFrame {

    /**
     * Creates new form Tut1_Exe3_checkbox
     */
    public Tut1_Exe3_checkbox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mca = new javax.swing.JCheckBox();
        bca = new javax.swing.JCheckBox();
        mscit = new javax.swing.JCheckBox();
        label_heading = new javax.swing.JLabel();
        print_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mca.setText("M.C.A");
        mca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcaActionPerformed(evt);
            }
        });

        bca.setText("B.C.A");
        bca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaActionPerformed(evt);
            }
        });

        mscit.setText("Msc.It");
        mscit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mscitActionPerformed(evt);
            }
        });

        label_heading.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        label_heading.setText("COURSES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(label_heading))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(bca)
                        .addGap(18, 18, 18)
                        .addComponent(mca)
                        .addGap(30, 30, 30)
                        .addComponent(mscit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(print_label, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mca)
                    .addComponent(mscit)
                    .addComponent(bca))
                .addGap(85, 85, 85)
                .addComponent(print_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaActionPerformed
        // TODO add your handling code here:
        String output = "Courses :";
        if(bca.isSelected() == true){
            output += " BCA ";
        }
        if(mca.isSelected() == true){
            output += " MCA ";
        }
        if(mscit.isSelected() == true){
            output += " Mscit ";
        }
        print_label.setText(output);
        
      
    }//GEN-LAST:event_bcaActionPerformed

    private void mcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String output = "Courses :";
        if(bca.isSelected() == true){
            output += " BCA ";
        }
        if(mca.isSelected() == true){
            output += " MCA ";
        }
        if(mscit.isSelected() == true){
            output += " Mscit ";
        }
        print_label.setText(output);
    }//GEN-LAST:event_mcaActionPerformed

    private void mscitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mscitActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String output = "Courses :";
        if(bca.isSelected() == true){
            output += " BCA ";
        }
        if(mca.isSelected() == true){
            output += " MCA ";
        }
        if(mscit.isSelected() == true){
            output += " Mscit ";
        }
        print_label.setText(output);
    }//GEN-LAST:event_mscitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tut1_Exe3_checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tut1_Exe3_checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tut1_Exe3_checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tut1_Exe3_checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tut1_Exe3_checkbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bca;
    private javax.swing.JLabel label_heading;
    private javax.swing.JCheckBox mca;
    private javax.swing.JCheckBox mscit;
    private javax.swing.JLabel print_label;
    // End of variables declaration//GEN-END:variables
}
