/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tut1;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class tut1_exe6 extends javax.swing.JFrame {

    /**
     * Creates new form tut1_exe6
     */
    public tut1_exe6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        color_group = new javax.swing.ButtonGroup();
        btn_red = new javax.swing.JRadioButton();
        btn_blue = new javax.swing.JRadioButton();
        btn_green = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Color Changing ");

        color_group.add(btn_red);
        btn_red.setText("RED");
        btn_red.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btn_redItemStateChanged(evt);
            }
        });
        btn_red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redActionPerformed(evt);
            }
        });

        color_group.add(btn_blue);
        btn_blue.setText("BLUE");
        btn_blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_blueActionPerformed(evt);
            }
        });

        color_group.add(btn_green);
        btn_green.setText("GREEN");
        btn_green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_greenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btn_red)
                .addGap(18, 18, 18)
                .addComponent(btn_blue)
                .addGap(30, 30, 30)
                .addComponent(btn_green)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_red)
                    .addComponent(btn_blue)
                    .addComponent(btn_green))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_redItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btn_redItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_redItemStateChanged

    private void btn_redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redActionPerformed
        // TODO add your handling code here:
        getContentPane().setBackground(Color.red);
    }//GEN-LAST:event_btn_redActionPerformed

    private void btn_blueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_blueActionPerformed
        // TODO add your handling code here:
        getContentPane().setBackground(Color.blue);
    }//GEN-LAST:event_btn_blueActionPerformed

    private void btn_greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_greenActionPerformed
        // TODO add your handling code here:
        getContentPane().setBackground(Color.green);
    }//GEN-LAST:event_btn_greenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tut1_exe6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tut1_exe6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tut1_exe6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tut1_exe6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tut1_exe6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_blue;
    private javax.swing.JRadioButton btn_green;
    private javax.swing.JRadioButton btn_red;
    private javax.swing.ButtonGroup color_group;
    // End of variables declaration//GEN-END:variables
}
