/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tut2;

import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rushikwin8
 */
public class Exe4_4 extends javax.swing.JFrame {

    /**
     * Creates new form Exe4_4
     */
    public Connection conn = null;

    public Exe4_4() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogBox = new javax.swing.JDialog();
        jLabel_Dialog_Rollno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Jdailog_Rollno = new javax.swing.JTextField();
        jButton_Dialog_FIND = new javax.swing.JButton();
        jDialog_MessageBox = new javax.swing.JDialog();
        jLabel1_MessageBox = new javax.swing.JLabel();
        jDialog_MessageBox_jButtonok = new javax.swing.JButton();
        jOptionPane_MeessageBox = new javax.swing.JOptionPane();
        jLabel_Rollno = new javax.swing.JLabel();
        jTextField_Rollno = new javax.swing.JTextField();
        jLabel_Rollno1 = new javax.swing.JLabel();
        jTextField_StudName = new javax.swing.JTextField();
        jLabel_Mark1 = new javax.swing.JLabel();
        jTextField_Mark1 = new javax.swing.JTextField();
        jTextField_Mark2 = new javax.swing.JTextField();
        jLabel_Mark2 = new javax.swing.JLabel();
        jTextField_Mark3 = new javax.swing.JTextField();
        jLabel_Mark3 = new javax.swing.JLabel();
        jButton_UPDATE = new javax.swing.JButton();
        jButton_ADD1 = new javax.swing.JButton();
        jButton_DELETE = new javax.swing.JButton();
        jButton_VIEW = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_output = new javax.swing.JTextArea();

        jDialogBox.setTitle("Dialog");
        jDialogBox.setAlwaysOnTop(true);
        jDialogBox.setBounds(new java.awt.Rectangle(100, 100, 300, 300));
        jDialogBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialogBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jDialogBox.setLocation(new java.awt.Point(100, 100));

        jLabel_Dialog_Rollno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Dialog_Rollno.setText("Enter Rollno :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Find Student");

        jButton_Dialog_FIND.setText("FIND");
        jButton_Dialog_FIND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Dialog_FINDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogBoxLayout = new javax.swing.GroupLayout(jDialogBox.getContentPane());
        jDialogBox.getContentPane().setLayout(jDialogBoxLayout);
        jDialogBoxLayout.setHorizontalGroup(
            jDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBoxLayout.createSequentialGroup()
                .addGroup(jDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogBoxLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Dialog_Rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Jdailog_Rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogBoxLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton_Dialog_FIND, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogBoxLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jDialogBoxLayout.setVerticalGroup(
            jDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBoxLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel_Dialog_Rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Jdailog_Rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton_Dialog_FIND, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jDialog_MessageBox.setAlwaysOnTop(true);
        jDialog_MessageBox.setBounds(new java.awt.Rectangle(100, 100, 400, 250));

        jLabel1_MessageBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_MessageBox.setText("Record Not Found");

        jDialog_MessageBox_jButtonok.setText("Ok");
        jDialog_MessageBox_jButtonok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialog_MessageBox_jButtonokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_MessageBoxLayout = new javax.swing.GroupLayout(jDialog_MessageBox.getContentPane());
        jDialog_MessageBox.getContentPane().setLayout(jDialog_MessageBoxLayout);
        jDialog_MessageBoxLayout.setHorizontalGroup(
            jDialog_MessageBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_MessageBoxLayout.createSequentialGroup()
                .addGroup(jDialog_MessageBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_MessageBoxLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1_MessageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog_MessageBoxLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jDialog_MessageBox_jButtonok, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jDialog_MessageBoxLayout.setVerticalGroup(
            jDialog_MessageBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_MessageBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_MessageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDialog_MessageBox_jButtonok, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Marksheet");
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Adobe Caslon Pro", 0, 24)); // NOI18N

        jLabel_Rollno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Rollno.setText("Rollno :");

        jLabel_Rollno1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Rollno1.setText("Student Name :");

        jLabel_Mark1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Mark1.setText("Mark1:");

        jLabel_Mark2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Mark2.setText("Mark2:");

        jLabel_Mark3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Mark3.setText("Mark3:");

        jButton_UPDATE.setText("UPDATE");

        jButton_ADD1.setText("ADD");
        jButton_ADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ADD1ActionPerformed(evt);
            }
        });

        jButton_DELETE.setText("DELETE");
        jButton_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DELETEActionPerformed(evt);
            }
        });

        jButton_VIEW.setText("VIEW");
        jButton_VIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VIEWActionPerformed(evt);
            }
        });

        jTextArea_output.setColumns(20);
        jTextArea_output.setRows(5);
        jScrollPane1.setViewportView(jTextArea_output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Rollno1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_StudName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Mark1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jTextField_Mark1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Mark2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jTextField_Mark2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Mark3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jTextField_Mark3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_ADD1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_UPDATE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_DELETE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_VIEW)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Rollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Rollno1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_StudName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Mark1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Mark1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Mark2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Mark2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Mark3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Mark3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_UPDATE)
                    .addComponent(jButton_ADD1)
                    .addComponent(jButton_DELETE)
                    .addComponent(jButton_VIEW))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VIEWActionPerformed
        // TODO add your handling code here:
        jDialogBox.setVisible(true);
    }//GEN-LAST:event_jButton_VIEWActionPerformed

    private void jButton_Dialog_FINDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Dialog_FINDActionPerformed
        // TODO add your handling code here:
        int i;

        //include driver
        try {

            //connect  to Db         
            String con_string = "jdbc:mysql://localhost:3306/student";
            conn = DriverManager.getConnection(con_string, "root", "");
            System.out.println("Connection Successfull !!");

            /*String select_query = "INSERT into stud values(?,?,?)";
            PreparedStatement stmt = conn.prepareStatement(select_query);
            stmt.setInt(1,4);
            stmt.setString(2, "Rushik");
            stmt.setInt(3, 18);*/
            String select_query = "SELECT Stud_Id,Stud_Name,Birth_Date,City,Course,Semester,Division FROM student_details WHERE Stud_Id = ? LIMIT 1";
            PreparedStatement stmt = conn.prepareStatement(select_query);
            Integer entered_rollno = Integer.parseInt(jTextField_Jdailog_Rollno.getText());

            stmt.setInt(1, entered_rollno);
            System.out.println(stmt);
            ResultSet rset = stmt.executeQuery();

            if (rset.next()) {
                //rset.next();
                String textarea_output = "Stud_Id: " + rset.getInt("Stud_Id")
                        + "\nStud Name : " + rset.getString("Stud_Name")
                        + "\nBirth Date : " + rset.getDate("Birth_Date")
                        + "\nCity : " + rset.getString("City")
                        + "\nCourse : " + rset.getString("Course")
                        + "\nSemester : " + rset.getString("Semester")
                        + "\nDivision : " + rset.getInt("Division");

                //set Text
                jTextField_Rollno.setText(rset.getString("Stud_Id"));
                jTextField_StudName.setText(rset.getString("Stud_Name"));

                //set Editable False
                jTextField_Rollno.setEditable(false);
                jTextField_StudName.setEditable(false);

                //set output to textarea
                jTextArea_output.setText(textarea_output);
                jDialogBox.dispose();
            } else {

                jLabel1_MessageBox.setText("No Record Found");
                jDialog_MessageBox.setVisible(true);
                jTextArea_output.setText("");
                jTextField_Rollno.setText("");
                jTextField_StudName.setText("");
                jTextField_Mark1.setText("");
                jTextField_Mark1.setText("");
                jTextField_Mark1.setText("");
                jDialogBox.dispose();
            }
            stmt.close();
           
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_Dialog_FINDActionPerformed

    private void jDialog_MessageBox_jButtonokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialog_MessageBox_jButtonokActionPerformed
        // TODO add your handling code here:
        jDialog_MessageBox.dispose();
    }//GEN-LAST:event_jDialog_MessageBox_jButtonokActionPerformed

    private void jButton_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DELETEActionPerformed
        // TODO add your handling code here:
        if (!jTextField_Rollno.getText().equals("")) {
            int dialogButton = jOptionPane_MeessageBox.YES_NO_OPTION;
            int dialogResult = jOptionPane_MeessageBox.showConfirmDialog(null, "Are You Sure.This will Not revert?", "Warning", dialogButton);
            jOptionPane_MeessageBox.setVisible(true);
            if (dialogResult == jOptionPane_MeessageBox.YES_OPTION) {
                
                System.out.println("Yes");
                // Saving code here
                try {
                    String delete_query = "DELETE FROM student_details WHERE  Stud_Id = ?";
                    PreparedStatement stmt = conn.prepareStatement(delete_query);

                    Integer entered_rollno = Integer.parseInt(jTextField_Jdailog_Rollno.getText());

                    stmt.setInt(1, entered_rollno);
                    System.out.println(stmt);
                    Integer result = stmt.executeUpdate();
                    System.out.println(result);
                    if (result != 0) {
                        jLabel1_MessageBox.setText(result.toString() + " Record deleted");
                        jDialog_MessageBox.setVisible(true);
                    }
                    else {
                    jLabel1_MessageBox.setText("No Record deleted");
                    jDialog_MessageBox.setVisible(true);}

                } catch (SQLException e) {
                    System.out.println(e);
                }
            } else {
                
            }

        } else {
         JOptionPane.showMessageDialog (null, "No Student Selected", "Title", JOptionPane.ERROR_MESSAGE);
           
        }


    }//GEN-LAST:event_jButton_DELETEActionPerformed

    private void jButton_ADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ADD1ActionPerformed
        // TODO add your handling code here:
        
        
        //get textfeild value
        
        Integer rollno = Integer.parseInt(jTextField_Rollno.getText());
        String name = jTextField_StudName.getText();
        Integer m1 = Integer.parseInt(jTextField_Mark1.getText());
        Integer m2 = Integer.parseInt(jTextField_Mark2.getText());
        Integer m3 = Integer.parseInt(jTextField_Mark3.getText());
        
        Integer total = m1 + m2 + m3;
        Float per = ( Float.parseFloat(total.toString()) / 3);
        
        //insert query
        
    }//GEN-LAST:event_jButton_ADD1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exe4_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exe4_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exe4_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exe4_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exe4_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ADD1;
    private javax.swing.JButton jButton_DELETE;
    private javax.swing.JButton jButton_Dialog_FIND;
    private javax.swing.JButton jButton_UPDATE;
    private javax.swing.JButton jButton_VIEW;
    private javax.swing.JDialog jDialogBox;
    private javax.swing.JDialog jDialog_MessageBox;
    private javax.swing.JButton jDialog_MessageBox_jButtonok;
    private javax.swing.JLabel jLabel1_MessageBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Dialog_Rollno;
    private javax.swing.JLabel jLabel_Mark1;
    private javax.swing.JLabel jLabel_Mark2;
    private javax.swing.JLabel jLabel_Mark3;
    private javax.swing.JLabel jLabel_Rollno;
    private javax.swing.JLabel jLabel_Rollno1;
    private javax.swing.JOptionPane jOptionPane_MeessageBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_output;
    private javax.swing.JTextField jTextField_Jdailog_Rollno;
    private javax.swing.JTextField jTextField_Mark1;
    private javax.swing.JTextField jTextField_Mark2;
    private javax.swing.JTextField jTextField_Mark3;
    private javax.swing.JTextField jTextField_Rollno;
    private javax.swing.JTextField jTextField_StudName;
    // End of variables declaration//GEN-END:variables
}
