/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tut2;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author rushikwin8
 */
public class Exe4_5 extends javax.swing.JFrame {

    /**
     * Creates new form Exe4_5
     */
    public Connection conn = null;
    ResultSet rset = null;
    public Exe4_5() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
             String con_string = "jdbc:mysql://localhost:3306/student";
            conn = DriverManager.getConnection(con_string, "root", "");
            System.out.println("Connection Successfull !!");

            /*String select_query = "INSERT into stud values(?,?,?)";
            PreparedStatement stmt = conn.prepareStatement(select_query);
            stmt.setInt(1,4);
            stmt.setString(2, "Rushik");
            stmt.setInt(3, 18);*/
            String select_query = "SELECT "
                    + "sd.Stud_Id,"
                    + "sd.Stud_Name,"
                    + "sd.Birth_Date,"
                    + "sd.City,sd.Course,"
                    + "sd.Semester,"
                    + "sd.Division,"
                    + "sm.Mark1,"
                    + "sm.Mark2,"
                    + "sm.Mark3,"
                    + "sm.Total,"
                    + "sm.Percentage,"
                    + "sm.Grade "
                    + "FROM student_details as sd "
                    + " JOIN student_marksheet as sm ON sd.Stud_Id= sm.Stud_Id";
            PreparedStatement stmt = conn.prepareStatement(select_query);
            System.out.println(stmt);
            this.rset = stmt.executeQuery();
            
            
            if (rset.next()) {
                //rset.next();
                jTextField_Rollno.setText(rset.getString("sd.Stud_Id"));
                jTextField_StudentName.setText(rset.getString("sd.Stud_Name"));
                jTextField_birthdate.setText(rset.getString("sd.Birth_Date"));
                jTextField_City.setText(rset.getString("sd.City"));
                jTextField_course.setText(rset.getString("sd.Course"));
                jTextField_sem.setText(rset.getString("sd.Semester"));
                jTextField_Div.setText(rset.getString("sd.Division"));
                
                jTextField_Mark1.setText(rset.getString("sm.Mark1"));
                jTextField_Mark2.setText(rset.getString("sm.Mark2"));
                jTextField_Mark3.setText(rset.getString("sm.Mark3"));
                jTextField_Total.setText(rset.getString("sm.Total"));
                jTextField_Per.setText(rset.getString("sm.Percentage"));
                jTextField_Grade.setText(rset.getString("sm.Grade"));
                
                                    
            } else {

                JOptionPane.showMessageDialog (null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Rollno = new javax.swing.JLabel();
        jTextField_Rollno = new javax.swing.JTextField();
        jTextField_StudentName = new javax.swing.JTextField();
        jLabel_studentName = new javax.swing.JLabel();
        jTextField_birthdate = new javax.swing.JTextField();
        jLabel_Birthdate = new javax.swing.JLabel();
        jTextField_City = new javax.swing.JTextField();
        jLabel_City = new javax.swing.JLabel();
        jTextField_course = new javax.swing.JTextField();
        jLabel_course = new javax.swing.JLabel();
        jTextField_sem = new javax.swing.JTextField();
        jLabel_sem = new javax.swing.JLabel();
        jTextField_Div = new javax.swing.JTextField();
        jLabel_Div = new javax.swing.JLabel();
        jLabel_Mark1 = new javax.swing.JLabel();
        jTextField_Mark1 = new javax.swing.JTextField();
        jLabel_Mark2 = new javax.swing.JLabel();
        jTextField_Mark2 = new javax.swing.JTextField();
        jLabel_Rollno9 = new javax.swing.JLabel();
        jTextField_Mark3 = new javax.swing.JTextField();
        jLabel_total = new javax.swing.JLabel();
        jTextField_Total = new javax.swing.JTextField();
        jLabel_Per = new javax.swing.JLabel();
        jTextField_Per = new javax.swing.JTextField();
        jLabel_Grade = new javax.swing.JLabel();
        jTextField_Grade = new javax.swing.JTextField();
        jButton_First = new javax.swing.JButton();
        jButton_Prev = new javax.swing.JButton();
        jButton_Last = new javax.swing.JButton();
        jButton_Next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Studet Record Navigation");
        setFont(new java.awt.Font("Adobe Caslon Pro", 0, 18)); // NOI18N

        jLabel_Rollno.setText("Rollno :");

        jLabel_studentName.setText("Student Name:");

        jLabel_Birthdate.setText("BirthDate :");

        jLabel_City.setText("City :");

        jLabel_course.setText("Course :");

        jLabel_sem.setText("Sem :");

        jLabel_Div.setText("Div :");

        jLabel_Mark1.setText("Mark1 :");

        jLabel_Mark2.setText("Mark2");

        jLabel_Rollno9.setText("Mark3");

        jLabel_total.setText("Total :");

        jLabel_Per.setText("Per :");

        jLabel_Grade.setText("Grade :");

        jButton_First.setText("|<");
        jButton_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FirstActionPerformed(evt);
            }
        });

        jButton_Prev.setText("<");
        jButton_Prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PrevActionPerformed(evt);
            }
        });

        jButton_Last.setText(">|");
        jButton_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LastActionPerformed(evt);
            }
        });

        jButton_Next.setText(">");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_First)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Prev))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Per, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_Per, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Next)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Last)))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Mark1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Mark1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Mark2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Mark2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Rollno9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Mark3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_City, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_City, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_course, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_course, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Div, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Div, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Rollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_City, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_course, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Div, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Mark1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Mark1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Mark2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Mark2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Rollno9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Mark3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Per, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_First)
                    .addComponent(jButton_Prev)
                    .addComponent(jButton_Next)
                    .addComponent(jButton_Last))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FirstActionPerformed
        // TODO add your handling code here:
        try{
        if (this.rset.first()) {
                //rset.next();
                jTextField_Rollno.setText(rset.getString("sd.Stud_Id"));
                jTextField_StudentName.setText(rset.getString("sd.Stud_Name"));
                jTextField_birthdate.setText(rset.getString("sd.Birth_Date"));
                jTextField_City.setText(rset.getString("sd.City"));
                jTextField_course.setText(rset.getString("sd.Course"));
                jTextField_sem.setText(rset.getString("sd.Semester"));
                jTextField_Div.setText(rset.getString("sd.Division"));
                
                jTextField_Mark1.setText(rset.getString("sm.Mark1"));
                jTextField_Mark2.setText(rset.getString("sm.Mark2"));
                jTextField_Mark3.setText(rset.getString("sm.Mark3"));
                jTextField_Total.setText(rset.getString("sm.Total"));
                jTextField_Per.setText(rset.getString("sm.Percentage"));
                jTextField_Grade.setText(rset.getString("sm.Grade"));
                
                                    
            } else {

                JOptionPane.showMessageDialog (null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton_FirstActionPerformed

    private void jButton_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LastActionPerformed
        // TODO add your handling code here:
         try{
        if (this.rset.last()) {
                //rset.next();
                jTextField_Rollno.setText(rset.getString("sd.Stud_Id"));
                jTextField_StudentName.setText(rset.getString("sd.Stud_Name"));
                jTextField_birthdate.setText(rset.getString("sd.Birth_Date"));
                jTextField_City.setText(rset.getString("sd.City"));
                jTextField_course.setText(rset.getString("sd.Course"));
                jTextField_sem.setText(rset.getString("sd.Semester"));
                jTextField_Div.setText(rset.getString("sd.Division"));
                
                jTextField_Mark1.setText(rset.getString("sm.Mark1"));
                jTextField_Mark2.setText(rset.getString("sm.Mark2"));
                jTextField_Mark3.setText(rset.getString("sm.Mark3"));
                jTextField_Total.setText(rset.getString("sm.Total"));
                jTextField_Per.setText(rset.getString("sm.Percentage"));
                jTextField_Grade.setText(rset.getString("sm.Grade"));
                
                                    
            } else {

                JOptionPane.showMessageDialog (null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_LastActionPerformed

    private void jButton_PrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PrevActionPerformed
        // TODO add your handling code here:
         try{
        if (this.rset.previous()) {
                //rset.next();
                jTextField_Rollno.setText(rset.getString("sd.Stud_Id"));
                jTextField_StudentName.setText(rset.getString("sd.Stud_Name"));
                jTextField_birthdate.setText(rset.getString("sd.Birth_Date"));
                jTextField_City.setText(rset.getString("sd.City"));
                jTextField_course.setText(rset.getString("sd.Course"));
                jTextField_sem.setText(rset.getString("sd.Semester"));
                jTextField_Div.setText(rset.getString("sd.Division"));
                
                jTextField_Mark1.setText(rset.getString("sm.Mark1"));
                jTextField_Mark2.setText(rset.getString("sm.Mark2"));
                jTextField_Mark3.setText(rset.getString("sm.Mark3"));
                jTextField_Total.setText(rset.getString("sm.Total"));
                jTextField_Per.setText(rset.getString("sm.Percentage"));
                jTextField_Grade.setText(rset.getString("sm.Grade"));
                
                                    
            } else {

                JOptionPane.showMessageDialog (null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_PrevActionPerformed

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        // TODO add your handling code here:
         try{
        if (this.rset.next()) {
                //rset.next();
                jTextField_Rollno.setText(rset.getString("sd.Stud_Id"));
                jTextField_StudentName.setText(rset.getString("sd.Stud_Name"));
                jTextField_birthdate.setText(rset.getString("sd.Birth_Date"));
                jTextField_City.setText(rset.getString("sd.City"));
                jTextField_course.setText(rset.getString("sd.Course"));
                jTextField_sem.setText(rset.getString("sd.Semester"));
                jTextField_Div.setText(rset.getString("sd.Division"));
                
                jTextField_Mark1.setText(rset.getString("sm.Mark1"));
                jTextField_Mark2.setText(rset.getString("sm.Mark2"));
                jTextField_Mark3.setText(rset.getString("sm.Mark3"));
                jTextField_Total.setText(rset.getString("sm.Total"));
                jTextField_Per.setText(rset.getString("sm.Percentage"));
                jTextField_Grade.setText(rset.getString("sm.Grade"));
                
                                    
            } else {

                JOptionPane.showMessageDialog (null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exe4_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exe4_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exe4_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exe4_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exe4_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_First;
    private javax.swing.JButton jButton_Last;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JButton jButton_Prev;
    private javax.swing.JLabel jLabel_Birthdate;
    private javax.swing.JLabel jLabel_City;
    private javax.swing.JLabel jLabel_Div;
    private javax.swing.JLabel jLabel_Grade;
    private javax.swing.JLabel jLabel_Mark1;
    private javax.swing.JLabel jLabel_Mark2;
    private javax.swing.JLabel jLabel_Per;
    private javax.swing.JLabel jLabel_Rollno;
    private javax.swing.JLabel jLabel_Rollno9;
    private javax.swing.JLabel jLabel_course;
    private javax.swing.JLabel jLabel_sem;
    private javax.swing.JLabel jLabel_studentName;
    private javax.swing.JLabel jLabel_total;
    private javax.swing.JTextField jTextField_City;
    private javax.swing.JTextField jTextField_Div;
    private javax.swing.JTextField jTextField_Grade;
    private javax.swing.JTextField jTextField_Mark1;
    private javax.swing.JTextField jTextField_Mark2;
    private javax.swing.JTextField jTextField_Mark3;
    private javax.swing.JTextField jTextField_Per;
    private javax.swing.JTextField jTextField_Rollno;
    private javax.swing.JTextField jTextField_StudentName;
    private javax.swing.JTextField jTextField_Total;
    private javax.swing.JTextField jTextField_birthdate;
    private javax.swing.JTextField jTextField_course;
    private javax.swing.JTextField jTextField_sem;
    // End of variables declaration//GEN-END:variables
}
