/*
 * Exe_8.java
 *
 * 
 */

package tutorial1;

import javax.swing.table.DefaultTableModel;

public class Exe_8 extends javax.swing.JFrame {

    /** Creates new form Exe_8 */
    private DefaultTableModel tableModel;
    int m1,m2,m3,per;
    String grd ;
    public Exe_8() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        roll_no = new javax.swing.JLabel();
        s_name = new javax.swing.JLabel();
        mark_1 = new javax.swing.JLabel();
        mark_2 = new javax.swing.JLabel();
        mark_3 = new javax.swing.JLabel();
        roll_no_text = new javax.swing.JTextField();
        s_name_text = new javax.swing.JTextField();
        mark_1_text = new javax.swing.JTextField();
        mark_2_text = new javax.swing.JTextField();
        mark_3_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        view_table = new javax.swing.JTable();
        view_det_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roll_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roll_no.setText("Roll No : ");

        s_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s_name.setText("Student Name : ");

        mark_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mark_1.setText("Mark 1 :");

        mark_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mark_2.setText("Mark 2 :");

        mark_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mark_3.setText("Mark 3 : ");

        tableModel = new DefaultTableModel( new Object [][] {
        },
        new String [] {
            "Roll No", "Student Name", "Mark 1", "Mark 2", "Mark 3", "Percentage", "Grade"
        });
        view_table.setModel(tableModel);
        jScrollPane1.setViewportView(view_table);

        view_det_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        view_det_btn.setText("View Details");
        view_det_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_det_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roll_no)
                            .addComponent(s_name)
                            .addComponent(mark_1)
                            .addComponent(mark_2)
                            .addComponent(mark_3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roll_no_text, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(s_name_text)
                            .addComponent(mark_1_text)
                            .addComponent(mark_2_text)
                            .addComponent(mark_3_text)
                            .addComponent(view_det_btn)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roll_no)
                    .addComponent(roll_no_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_name)
                    .addComponent(s_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mark_1)
                    .addComponent(mark_1_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mark_2)
                    .addComponent(mark_2_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mark_3)
                    .addComponent(mark_3_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_det_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void view_det_btnActionPerformed(java.awt.event.ActionEvent evt) {                                             

        m1 = Integer.valueOf(mark_1_text.getText()).intValue();
        m2 = Integer.valueOf(mark_2_text.getText()).intValue();
        m3 = Integer.valueOf(mark_3_text.getText()).intValue();
        per = (m1 + m2 +m3)/3;
        if(m1 >= 35 && m2 >= 35 && m3 >= 35){
            if (per >= 90) {
                grd = "O";
            }
            else if(per >=80 && per<=90){
                grd = "A";
            }
            else if(per >=70 && per<=80){
                grd = "B";
            }
            else if(per >=60 && per<=70){
                grd = "C";
            }
            else if(per >=50 && per<=60){
                grd = "D";
            }
            else{
                grd = "E";
            }
        }
        else
        {
            per = 0;
            grd = "Fail";
        }
        int count = tableModel.getRowCount()+1;
        tableModel.addRow(new Object[]{new Integer(roll_no_text.getText()), s_name_text.getText(), new Float(mark_1_text.getText()), new Float(mark_2_text.getText()), new Float(mark_3_text.getText()), new Float(per)+"%", grd});

        roll_no_text.setText("");
        s_name_text.setText("");
        mark_1_text.setText("");
        mark_2_text.setText("");
        mark_3_text.setText("");
    }                                            

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Exe_8().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mark_1;
    private javax.swing.JTextField mark_1_text;
    private javax.swing.JLabel mark_2;
    private javax.swing.JTextField mark_2_text;
    private javax.swing.JLabel mark_3;
    private javax.swing.JTextField mark_3_text;
    private javax.swing.JLabel roll_no;
    private javax.swing.JTextField roll_no_text;
    private javax.swing.JLabel s_name;
    private javax.swing.JTextField s_name_text;
    private javax.sw ing.JButton view_det_btn;
    private javax.swing.JTable view_table;
    // End of variables declaration                   

}
